name: Build and publish Docker image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/aottr/rallly-cleaned:${{ github.sha }} --tag ghcr.io/aottr/rallly-cleaned:latest

      - name: Publish Docker image to Github Packages
        shell: bash
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          echo $PAT | docker login ghcr.io --username alexottr --password-stdin
          docker push ghcr.io/aottr/rallly-cleaned --all-tags
          docker logout
